# Stage 1
FROM maven:3.8.4-openjdk-8 AS build

WORKDIR /app
COPY pom.xml .
RUN mvn test


COPY src ./src
RUN mvn package


FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=build /app/target/accenture-techhub-0.0.1-SNAPSHOT.war .

EXPOSE 8080

CMD ["java", "-jar", "accenture-techhub-0.0.1-SNAPSHOT.war"]
